### ISSUE TITLE
[Bug] Does not run

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Programmer-Technologies/NoteTaker-py#2]
When I try to run the code using Python 3.10.6 it states:
```
(.venv) H:\Files_KEEP\01-Programming\langs\Python\projects\Third-Party-Ones\NoteTaker-py>.\transcribe.py
Traceback (most recent call last):
  File "H:\Files_KEEP\01-Programming\langs\Python\projects\Third-Party-Ones\NoteTaker-py\transcribe.py", line 1, in <module>
    import whisper
  File "H:\Files_KEEP\01-Programming\langs\Python\projects\Third-Party-Ones\NoteTaker-py\.venv\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

pip list:
```
Package               Version
--------------------- ---------
certifi               2023.7.22
charset-normalizer    3.2.0
click                 8.1.7
colorama              0.4.6
filelock              3.12.3
fsspec                2023.6.0
huggingface-hub       0.16.4
idna                  3.4
joblib                1.3.2
nltk                  3.8.1
numpy                 1.24.2
packaging             23.1
Pillow                10.0.0
pip                   22.2.1
pytube                12.1.2
PyYAML                6.0.1
regex                 2023.8.8
requests              2.31.0
scikit-learn          1.2.1
scipy                 1.11.2
sentence-transformers 2.2.2
sentencepiece         0.1.99
setuptools            63.2.0
six                   1.16.0
summarizer            0.0.7
threadpoolctl         3.2.0
tokenizers            0.13.3
torch                 1.13.1
torchvision           0.14.1
tqdm                  4.66.1
transformers          4.26.1
typing_extensions     4.7.1
urllib3               2.0.4
whisper               1.1.10
```

**Comment by IbrahimHabibeh** [comment]
Make sure to install Whisper using the following command, as the requirements.txt file is inadequate: 

pip install -U openai-whisper

**Comment by IbrahimHabibeh** [comment]
My apologies, this is not an import error. Let me look further into the issue and I will get back

**Comment by IbrahimHabibeh** [comment]
It looks like it has to do with the way that whisper was installed. Try running this command:

pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git

**Comment by PiggiesGoSqueal** [comment]
Admittedly I'm probably not going to try this as I no longer need it but I appreciate the prompt reply.
